---
- name:         Ensure /tmp/toto directories are created
  file:
    path:       "{{ item }}"
    state:      directory
    mode:       "0755"
  loop:
    - /tmp/toto

- name: install curl
  yum:
    name: curl
    state: present
    update_cache: yes
